### PR TITLE
SSL-enabled WorkflowClient with CA cert as param and overriding authority name

### PR DESCRIPTION
**Pull request by Aymalla**
## What was changed?

A new sample has been added (ssl/SslEnabledWorkerCustomCA) that shows how to start a WorkflowClient that connects to temporal cluster with mTLS enabled created by ([tls-simple sample](https://github.com/temporalio/samples-server/tree/main/tls/tls-simple));

SslEnabledWorkerCustomCA demonstrates:
- Passing a CA certificate file as parameter
- Overriding the authority name used for TLS handshakes (if needed)

## Why?

To help developers to create mTLS enabled local dev environment using [tls-simple sample](https://github.com/temporalio/samples-server/tree/main/tls/tls-simple) to test their workflows.

Address help for issues like: 
https://community.temporal.io/t/how-to-disable-host-name-verification/2808
https://community.temporal.io/t/how-to-set-tls-server-for-java-sdk-connection-option/6575

## Checklist

1. Closes 

2. How was this tested:

Manually using these steps mentioned in ssl/ReadME.md  [samples/ssl/ReadME.md](https://github.com/Aymalla/temporal-samples-java/blob/aym/sslcontext-custom-ca/src/main/java/io/temporal/samples/ssl/README.md)

3. Any docs updates needed? No

### CODE REVIEW

**Comment by tsurdilo** [comment]
@Aymalla thanks for the pr!

**Comment by Aymalla** [comment]
> @Aymalla thanks for the pr!

Hi @tsurdilo, 
I hope you're doing well. I wanted to check in on the  status of this PR.

**Comment by tsurdilo** [comment]
@Aymalla hi yeah it looks good. I think the project structure changed since this pr was opened. Mind rebasing and adding it to the "core" dir? Thanks.

**Comment by tsurdilo** [comment]
Hi, not sure the rebase was correct? Maybe better to update main branch and then add your changes in a new pr? Wdyt

**Comment by Aymalla** [comment]
@tsurdilo merge is Done

**Review by tsurdilo — APPROVED** [review]

**Comment by tsurdilo** [comment]
Thanks for merging. LGTM
@antmendoza can you please review as well? Thanks.

**Review by antmendoza — APPROVED** [review]
LGTM too, thanks @Aymalla

**Pull request merged**
