### PR TITLE
Update HelloSearchAttribute sample to use typed SA api

### PR DESCRIPTION
**Pull request by tsurdilo**
updates hello SA sample to use typed api

### CODE REVIEW

**Comment by Quinn-With-Two-Ns** [comment]
Is this sample not sufficient? https://github.com/temporalio/samples-java/blob/main/core/src/main/java/io/temporal/samples/hello/HelloTypedSearchAttributes.java

**Comment by tsurdilo** [comment]
Yes only thing is that the HelloSearchAttribute one had deprecated api calls, maybe worth still changing. Wdyt?

**Comment by tsurdilo** [comment]
I think we can remove the old one (one i changed here) but just update the test to use HelloTypedSearchAttributes, wdyt?

**Comment by Quinn-With-Two-Ns** [comment]
@tsurdilo sorry for the late reply, go sick and forgot about this PR, I think it makes sense to mark `HelloSearchAttribute`  as deprecated or delete and rename `HelloTypedSearchAttributes` to `HelloSearchAttribute`

Originally I kept  `HelloSearchAttribute`  because  some users don't upgrade the SDK often so they might not have the new API .

**Pull request closed without merging**
