### PR TITLE
Fixing README

### PR DESCRIPTION
**Pull request by edmondop**
As a part of https://github.com/temporalio/samples-go/issues/239 I found this :)

### CODE REVIEW

**Review by tsurdilo — APPROVED** [review]

**Comment by Spikhalskiy** [comment]
@edmondop thanks for the contribution!

**Comment by tsurdilo** [comment]
Thanks! Will merge when buildkite finishes

**Review by Spikhalskiy — APPROVED** [review]

**Comment by edmondop** [comment]
@tsurdilo @antmendoza @Spikhalskiy  I found similar problems in the README comments for the other polling examples, as well as wrongly formatted comments that were really making me struggle. Apologies for asking a new approval

**Comment by Spikhalskiy** [comment]
@edmondop could you please fix the formatting by applying `./gradlew :spotlessApply`?

**Comment by Spikhalskiy** [comment]
@edmondop Line breaks in javadocs by themselves are meaningless. If you want to format the comment, please use html tags: https://stackoverflow.com/questions/6478777/how-to-create-multiple-levels-of-indentation-in-javadoc

**Pull request merged**
